name: Build and Test
on: [push, pull_request]
permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x, 18.x]

    steps:
    - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 #v3.5.3
    - name: Use nodejs ${{ matrix.node-version }}
      uses: actions/setup-node@e33196f7422957bea03ed53f6fbb155025ffc7b8 #v3.7.0
      with:
        node-version: ${{ matrix.node-version }}

    - name: yarn
      run: yarn install
    - name: linter checks
      run: yarn lint
    - name: tests
      env:
        CI: yes
      run: yarn test
